version: '3.1'

services:
  dbsql:
    container_name: dbsql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elearning
    ports:
      - '3308:3306'
    networks:
      - learning-sql
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
  
  #Elearning App
  app:
    container_name: "e-learning"
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbsql:3306/elearning?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - learning-sql
    #   - spring
    depends_on:
      - dbsql
    ports:
      - 8080:8080
    #command: /home/gradle/buildWorkspace/app/build/distributions/app/bin/app

 
networks:
  learning-sql:

volumes:
  dbsql: